ARG REACT_APP_STRIPE_SECRET_KEY
ARG REACT_APP_FIREBASE_KEY

# set working directory
FROM node:18.16.0 as build
WORKDIR /app
ENV REACT_APP_STRIPE_SECRET_KEY="xxxxx"
ENV REACT_APP_FIREBASE_KEY="xxxxx"
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build
FROM nginx:1.19
COPY ./nginx.conf /etc/nginx/nginx.conf
ENV REACT_APP_STRIPE_SECRET_KEY="xxxxx"
ENV REACT_APP_FIREBASE_KEY="xxxxx"
COPY --from=build /app/build /usr/share/nginx/html